# Generated by Django 4.2.30 on 2026-08-08 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('clase', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], default='gasto', max_length=10)),
                ('orden', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías (plan de cuentas)',
                'ordering': ['clase', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CuentaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(help_text='Identificador estable: mercado_pago, bancoestado, scotiabank…', max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('pasarela', 'Pasarela de pago'), ('banco', 'Cuenta bancaria'), ('efectivo', 'Efectivo (caja)'), ('tarjeta_credito', 'Tarjeta de crédito'), ('billetera', 'Billetera digital')], max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Cuenta financiera',
                'verbose_name_plural': 'Cuentas financieras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SaldoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Primer día del mes al que corresponde el cierre.')),
                ('saldo_cierre', models.DecimalField(decimal_places=0, max_digits=14)),
                ('fuente', models.CharField(choices=[('captura', 'Captura de pantalla'), ('cartola', 'Cartola (PDF/CSV)'), ('manual', 'Digitación manual')], default='captura', max_length=10)),
                ('notas', models.CharField(blank=True, default='', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='finanzas.cuentafinanciera')),
            ],
            options={
                'verbose_name': 'Saldo mensual',
                'verbose_name_plural': 'Saldos mensuales',
                'ordering': ['-periodo', 'cuenta__nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('clase', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('traspaso', 'Traspaso entre cuentas propias')], db_index=True, max_length=10)),
                ('sentido', models.CharField(choices=[('entra', 'Entra'), ('sale', 'Sale')], max_length=6)),
                ('monto', models.DecimalField(decimal_places=0, help_text='Siempre positivo; el signo lo pone clase/sentido.', max_digits=12)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('fuente', models.CharField(choices=[('api', 'API verificada'), ('correo', 'Aviso por correo'), ('captura', 'Captura de pantalla'), ('manual', 'Digitación manual')], db_index=True, default='manual', max_length=10)),
                ('referencia', models.CharField(blank=True, db_index=True, default='', help_text='Id externo (pago MP, nº operación de cartola, o id de carga histórica). Es la llave de idempotencia: la misma referencia no se carga dos veces.', max_length=100)),
                ('fecha_estimada', models.BooleanField(default=False, help_text='True cuando la fuente solo dio el mes (ej. correos agregados): la fecha es el día 1 y no debe usarse para análisis diario.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, help_text='Obligatoria para ingresos/gastos; vacía en traspasos.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finanzas.categoriafinanciera')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finanzas.cuentafinanciera')),
                ('traspaso_par', models.ForeignKey(blank=True, help_text='La otra pierna del traspaso. Un traspaso son SIEMPRE dos líneas que suman cero: sale de una cuenta y entra a la otra.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finanzas.movimientofinanciero')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='saldomensual',
            constraint=models.UniqueConstraint(fields=('cuenta', 'periodo'), name='finanzas_saldo_unico_por_mes'),
        ),
        migrations.AddConstraint(
            model_name='movimientofinanciero',
            constraint=models.CheckConstraint(check=models.Q(('monto__gt', 0)), name='finanzas_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='movimientofinanciero',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia', ''), _negated=True), fields=('referencia',), name='finanzas_referencia_unica'),
        ),
    ]
