# Generated by Django 4.2.30 on 2026-08-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_categoriafinanciera_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriafinanciera',
            name='grupo',
            field=models.CharField(choices=[('personal', 'Sueldos de personal'), ('masajistas', 'Honorarios masajistas'), ('energia', 'Energía eléctrica'), ('marketing', 'Marketing'), ('infra_web', 'Infraestructura web e IA'), ('admin_fin', 'Administración y financieros'), ('operacion', 'Operación e insumos'), ('combustibles', 'Combustibles'), ('impuestos', 'Impuestos'), ('devoluciones', 'Devoluciones a clientes'), ('personales_martin', 'Personales Martín'), ('personales_alda', 'Personales Alda'), ('personales_jorge', 'Personales Jorge'), ('ingresos', 'Ingresos'), ('otros', 'Otros / por clasificar')], db_index=True, default='otros', max_length=30),
        ),
    ]
