# Generated by Django 4.2.30 on 2026-04-23 19:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Depende solo de ventas.Producto (existe desde hace mucho).
        # Apuntamos a 0083 (confirmada aplicada en prod y local) para evitar
        # arrastrar 0084_servicehistory*, que es archivo huérfano de AR-034 drift.
        ('ventas', '0083_servicio_producto_imagenes_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Si está inactivo, no se descuentan componentes al venderlo.')),
                ('descontar_componentes_auto', models.BooleanField(default=True, help_text='Si está activo, al vender este producto se descuentan automáticamente los componentes.', verbose_name='Descontar componentes automáticamente')),
                ('notas', models.TextField(blank=True, help_text='Notas internas sobre la composición del kit (ingredientes, recetas, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto_compuesto', models.OneToOneField(help_text='El producto "kit" que se vende al cliente (ej: Tabla de Quesos).', on_delete=django.db.models.deletion.CASCADE, related_name='kit', to='ventas.producto', verbose_name='Producto compuesto')),
            ],
            options={
                'verbose_name': 'Kit',
                'verbose_name_plural': 'Kits (productos compuestos)',
                'ordering': ['producto_compuesto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='KitComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_por_unidad', models.DecimalField(decimal_places=3, help_text='Cantidad del componente consumida por cada unidad vendida del kit.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='kits.kit')),
                ('producto_componente', models.ForeignKey(help_text='El producto interno que se descuenta del inventario.', on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_kits', to='ventas.producto', verbose_name='Producto componente')),
            ],
            options={
                'verbose_name': 'Componente del kit',
                'verbose_name_plural': 'Componentes del kit',
                'ordering': ['kit', 'producto_componente__nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='kitcomponente',
            constraint=models.UniqueConstraint(fields=('kit', 'producto_componente'), name='uq_kit_componente'),
        ),
    ]
