# Generated by Django 4.2.30 on 2026-08-09 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0132_servicehistory_campaignemailtemplate_clientepremio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtesaniaPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='El código del papel (45, 58, … 1060). Único por pieza.', max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=160)),
                ('precio', models.DecimalField(decimal_places=0, help_text='Precio de lista en pesos. Al vender se puede ajustar.', max_digits=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible en sala'), ('bodega', 'En bodega'), ('vendida', 'Vendida'), ('merma', 'Merma'), ('regalo', 'Regalo / entrega sin cobro'), ('baja', 'Baja')], db_index=True, default='disponible', max_length=12)),
                ('foto', models.ImageField(blank=True, help_text='Opcional: foto con el celular.', null=True, upload_to='artesanias/')),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('venta_monto', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('venta_fecha', models.DateField(blank=True, null=True)),
                ('venta_forma_pago', models.CharField(blank=True, default='', max_length=30)),
                ('notas', models.CharField(blank=True, default='', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('venta_reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artesanias_vendidas', to='ventas.ventareserva')),
            ],
            options={
                'verbose_name': 'Pieza de artesanía',
                'verbose_name_plural': 'Piezas de artesanía',
                'ordering': ['-creado_en'],
            },
        ),
    ]
