# Generated by Django 4.2.30 on 2026-08-09 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # Anclada a la última migración REAL en git (la 0132 es drift local
        # no trackeado — misma trampa que la 0001, ver memoria del drift).
        ('ventas', '0131_masajeslandingconfig_video_recorrido'),
        ('artesanias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artesaniapieza',
            name='venta_linea',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artesania_pieza', to='ventas.reservaproducto'),
        ),
    ]
