# Generated by Django 4.2.30 on 2026-07-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aremko_cli_sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEORankingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('success', models.BooleanField(default=False, help_text='True si el fetch a aremko-cli respondió 200 con datos utilizables para esta keyword.')),
                ('keyword', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('target_domain', models.CharField(blank=True, default='aremko.cl', max_length=200)),
                ('location_name', models.CharField(blank=True, default='', help_text='location_name de DataForSEO usado en este check (ej. "Puerto Varas,Los Lagos,Chile").', max_length=100)),
                ('found', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(blank=True, help_text='Posición ORGÁNICA (cuenta solo resultados type=organic, 1-indexed). Null si no encontrado.', null=True)),
                ('rank_absolute', models.PositiveIntegerField(blank=True, help_text='Posición absoluta en el SERP completo (incluye knowledge graph, imágenes, local pack, etc. antes) — referencia, no usar para comparar ciclo a ciclo.', null=True)),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('competitors_above', models.JSONField(blank=True, default=list, help_text='Dominios orgánicos que aparecen antes del target (máx 10) para esta keyword.')),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Snapshot ranking SEO (aremko-cli)',
                'verbose_name_plural': 'Snapshots ranking SEO (aremko-cli)',
                'db_table': 'aremko_cli_sync_seorankingsnapshot',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['keyword', '-fetched_at'], name='aremko_cli__keyword_62d390_idx')],
            },
        ),
    ]
