# Generated by Django 4.2.30 on 2026-06-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SugerenciaAgenteWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_message_id', models.CharField(db_index=True, help_text='ID Meta del entrante que esta sugerencia responde (idempotencia/cache).', max_length=128, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('texto', models.TextField(blank=True, help_text='Borrador sugerido (vacío si escala a humano).')),
                ('escalar', models.BooleanField(default=False, help_text='True = derivar a persona; no se sugiere texto.')),
                ('motivo_escalar', models.CharField(blank=True, max_length=200)),
                ('modo', models.CharField(blank=True, max_length=20)),
                ('modelo', models.CharField(blank=True, max_length=120)),
                ('error', models.CharField(blank=True, help_text='Si el LLM falló; activa el fallback seguro.', max_length=200)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('enviada', models.BooleanField(default=False, help_text='True cuando el borrador se usó para responder (lo marcará el outbound en fases 2-3).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sugerencia Agente WhatsApp',
                'verbose_name_plural': 'Sugerencias Agente WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppAgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False, help_text='Interruptor general. Si está apagado, no se genera ninguna sugerencia.', verbose_name='Agente activo')),
                ('modo', models.CharField(choices=[('borrador', 'Borrador asistido (Fase 1) — genera sugerencia, humano envía'), ('auto_info', 'Auto solo informativo (Fase 2) — auto-envía info, escala lo transaccional'), ('auto', 'Auto completo (Fase 3) — responde dentro de alcance')], default='borrador', help_text='Fase 1 = borrador (recomendado para empezar). El auto-envío llega en fases 2-3.', max_length=20)),
                ('persona_tono', models.TextField(default='Eres el asistente virtual de Aremko Spa Boutique, en Puerto Varas, Chile ("aguas calientes junto al río"). Hablas en español de Chile, cálido y cercano, breve, con buena onda y sin sonar robótico. Representas a un spa boutique de cabañas y tinas calientes junto al río.', help_text='Voz de marca / personalidad. Es el bloque 1 del system prompt (editable sin redeploy).')),
                ('link_reserva', models.URLField(default='https://www.aremko.cl/', help_text='Link oficial de reservas al que el agente deriva (nunca confirma reservas él mismo).', max_length=300)),
                ('model_name', models.CharField(blank=True, default='', help_text='ID OpenRouter (ej. anthropic/claude-haiku-4.5). Vacío = usa DPV_LLM_MODEL de env.', max_length=120)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.4, help_text='Creatividad del modelo. Bajo (0.2-0.5) = más preciso y predecible (recomendado).', max_digits=3)),
                ('max_tokens', models.PositiveSmallIntegerField(default=350, help_text='Tope de tokens de salida. WhatsApp quiere respuestas cortas.')),
                ('history_window', models.PositiveSmallIntegerField(default=6, help_text='Cuántos mensajes recientes de la conversación se le pasan como contexto.')),
                ('pausa_horas_tras_humano', models.PositiveSmallIntegerField(default=12, help_text='Horas que el agente se calla en un chat después de que un humano respondió ahí.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Agente WhatsApp',
            },
        ),
    ]
