# Generated by Django 4.2.30 on 2026-06-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AusenciaEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('ultimo_envio', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Ausencia enviada',
                'verbose_name_plural': 'Ausencias enviadas',
            },
        ),
        migrations.AddField(
            model_name='whatsappagentconfig',
            name='ausencia_activa',
            field=models.BooleanField(default=False, help_text='Si está activo, a cada cliente que escribe se le responde una frase fija y NO se genera borrador del agente (la ausencia tiene precedencia).', verbose_name='Mensaje de ausencia activo'),
        ),
        migrations.AddField(
            model_name='whatsappagentconfig',
            name='ausencia_anti_spam_horas',
            field=models.PositiveSmallIntegerField(default=6, help_text='No repetir la frase de ausencia a la misma conversación dentro de estas horas (0 = responder a cada mensaje).'),
        ),
        migrations.AddField(
            model_name='whatsappagentconfig',
            name='ausencia_mensaje',
            field=models.TextField(default='¡Hola! 🌿 Gracias por escribir a Aremko Spa Boutique. En este momento no estamos atendiendo por este chat. Puedes reservar y pagar online —masajes, tinas calientes y alojamiento— en www.aremko.cl, disponible las 24 horas. Apenas retomemos la atención te respondemos por aquí. ¡Gracias por tu paciencia! 🙏', help_text='Frase fija que se auto-responde cuando la ausencia está activa.'),
        ),
    ]
