# Generated by Django 4.2.30 on 2026-06-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_agent', '0002_ausenciaenviada_whatsappagentconfig_ausencia_activa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappagentconfig',
            name='conocimiento',
            field=models.TextField(blank=True, default='', help_text='Reglas y correcciones que el agente debe respetar SIEMPRE (autoridad máxima, por sobre el catálogo). Una regla por línea. Ej: "Las tinas se cobran POR PERSONA, capacidad 1 a 4." / "No ofrecer el producto Cacao por este chat." Editable sin redeploy.', verbose_name='Conocimiento y correcciones'),
        ),
    ]
