# Generated by Django 4.2.30 on 2026-06-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_agent', '0003_whatsappagentconfig_conocimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('wa_message_id', models.CharField(blank=True, db_index=True, help_text='Referencia del mensaje/borrador (el entrante que se respondía).', max_length=128)),
                ('borrador', models.TextField(blank=True, help_text='Lo que el agente propuso.')),
                ('enviado', models.TextField(blank=True, help_text='Lo que Deborah realmente envió.')),
                ('editado', models.BooleanField(db_index=True, default=False, help_text='True si lo enviado difiere del borrador (hubo corrección).')),
                ('procesado', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Feedback del agente',
                'verbose_name_plural': 'Feedback del agente',
                'ordering': ['-created_at'],
            },
        ),
    ]
