# Generated by Django 4.2.30 on 2026-06-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Última migración REAL de ventas (NO el dump de drift autogenerado, que se borró).
        # Solo necesitamos que exista la tabla ventas_servicio para la M2M.
        ('ventas', '0124_seguimiento_masaje_auditoria_outbox'),
        ('whatsapp_agent', '0004_agentefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappagentconfig',
            name='servicios_complementarios',
            field=models.ManyToManyField(blank=True, help_text='Tinas/servicios que se AGREGAN a una reserva (ej. tina de niño, tina fría, decoraciones), no se arriendan solos. El agente NO los ofrece como opción principal ni los lista en disponibilidad.', related_name='+', to='ventas.servicio', verbose_name='Servicios complementarios (no se ofrecen como principales)'),
        ),
    ]
