# Generated by Django 4.2.30 on 2026-06-14 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_agent', '0005_whatsappagentconfig_servicios_complementarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugerenciaAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('tipo', models.CharField(choices=[('hecho_catalogo', 'Hecho de catálogo (precio/disponibilidad) — aprueba Jorge'), ('regla', 'Regla/política → Conocimiento del agente'), ('tono', 'Tono/redacción'), ('puntual', 'Puntual / typo (no se propone)')], db_index=True, max_length=20)),
                ('texto_propuesto', models.TextField(blank=True, help_text='Para `regla`: la línea a agregar al Conocimiento. Para `hecho_catalogo`: descripción del cambio sugerido al catálogo.')),
                ('ref_catalogo', models.CharField(blank=True, help_text='Para hecho_catalogo: ítem/campo/valor sugerido (ej. "Tina Calbuco · precio · 30000").', max_length=200)),
                ('motivo', models.CharField(blank=True, help_text='Por qué se clasificó así.', max_length=300)),
                ('borrador', models.TextField(blank=True)),
                ('enviado', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('descartada', 'Descartada')], db_index=True, default='pendiente', max_length=12)),
                ('aplicado_info', models.CharField(blank=True, help_text='Qué pasó al aprobar.', max_length=300)),
                ('modelo', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resuelto_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias', to='whatsapp_agent.agentefeedback')),
            ],
            options={
                'verbose_name': 'Sugerencia de aprendizaje',
                'verbose_name_plural': 'Sugerencias de aprendizaje',
                'ordering': ['-created_at'],
            },
        ),
    ]
