# Generated by Django 4.2 on 2024-11-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0023_alter_pago_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('efectivo', 'Efectivo'), ('webpay', 'WebPay'), ('descuento', 'Descuento'), ('giftcard', 'GiftCard'), ('flow', 'FLOW'), ('mercadopago', 'MercadoPago'), ('scotiabank', 'Tranferencia ScotiaBank'), ('bancoestado', 'Transferencia BancoEstado'), ('cuentarut', 'Transferencia CuentaRut'), ('machjorge', 'mach jorge'), ('machalda', 'mach alda'), ('bicegoalda', 'bicego alda'), ('bcialda', 'bci alda'), ('andesalda', 'andes alda'), ('mercadopagoaremko', 'mercadopago aremko'), ('scotiabankalda', 'scotiabank alda'), ('copecjorge', 'copec jorge'), ('copecalda', 'copec alda'), ('copecmartin', 'copec martin')], max_length=50),
        ),
    ]
