# Generated by Django 5.0.1 on 2024-12-02 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0025_alter_pago_metodo_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientocliente',
            options={'verbose_name': 'Movimiento de Cliente', 'verbose_name_plural': 'Movimientos de Clientes'},
        ),
        migrations.RemoveField(
            model_name='movimientocliente',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='movimientocliente',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movimientocliente',
            name='venta_reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.ventareserva'),
        ),
        migrations.AlterField(
            model_name='movimientocliente',
            name='tipo_movimiento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movimientocliente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
