# Generated by Django 5.0.1 on 2024-12-02 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0026_allow_null_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientocliente',
            options={},
        ),
        migrations.AlterField(
            model_name='movimientocliente',
            name='venta_reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.ventareserva'),
        ),
    ]
