# Generated by Django 5.0.1 on 2024-12-02 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0026_alter_movimientocliente_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientocliente',
            old_name='comentarios',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='movimientocliente',
            name='venta_reserva',
        ),
    ]
