# Generated by Django 5.0.1 on 2024-12-02 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0027_allow_null_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientocliente',
            old_name='descripcion',
            new_name='comentarios',
        ),
        migrations.AddField(
            model_name='movimientocliente',
            name='venta_reserva',
            field=models.ForeignKey(default=1111, on_delete=django.db.models.deletion.CASCADE, to='ventas.ventareserva'),
            preserve_default=False,
        ),
    ]
