# Generated by Django 4.2 on 2025-02-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0027_allow_null_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaservicio',
            name='hora_inicio',
            field=models.CharField(default='14:00', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='capacidad_maxima',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='servicio',
            name='horario_apertura',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='horario_cierre',
            field=models.TimeField(default='23:59'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='slots_disponibles',
            field=models.JSONField(default=list, help_text='Horarios disponibles en formato HH:MM'),
        ),
        migrations.AlterField(
            model_name='reservaservicio',
            name='fecha_agendamiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='duracion',
            field=models.PositiveIntegerField(help_text='Duración en minutos'),
        ),
    ]
