# Generated by Django 5.0.1 on 2024-12-02 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0028_allow_null_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocliente',
            name='venta_reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.ventareserva'),
        ),
    ]
