# Generated by Django 4.2 on 2025-02-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0029_rename_duracion_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el servicio está disponible para reservas'),
        ),
    ]
