# Generated by Django 4.2 on 2025-02-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0029_convert_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='duracion',
            field=models.PositiveIntegerField(help_text='Duración en minutos'),
        ),
    ]
