# Generated by Django 4.2 on 2025-02-24 22:55

from django.db import migrations, models
import ventas.models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0030_servicio_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='slots_disponibles',
            field=models.JSONField(default=list, help_text="Horarios disponibles en formato ['09:00', '10:00', ...]", validators=[ventas.models.validate_slots_format]),
        ),
    ]
