# Generated by Django 4.2 on 2025-04-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0030_servicio_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaservicio',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de la imagen para la categoría', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de la imagen para el servicio', max_length=500, null=True),
        ),
    ]
