# Generated by Django 4.2 on 2025-02-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0031_alter_servicio_slots_disponibles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaservicio',
            name='cantidad_personas',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='slots_disponibles',
            field=models.JSONField(default=list),
        ),
    ]
