# Generated by Django 4.2 on 2025-04-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0031_categoriaservicio_imagen_url_servicio_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaservicio',
            name='imagen_url',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='categoriaservicio',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen para la categoría', null=True, upload_to='categorias/'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen para el servicio', null=True, upload_to='servicios/'),
        ),
    ]
