# Generated by Django manually because makemigrations failed to detect changes.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0032_remove_categoriaservicio_imagen_url_and_more'), # Depends on the previous migration
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaservicio',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen para la categoría', null=True, upload_to='categorias/'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen para el servicio', null=True, upload_to='servicios/'),
        ),
    ]
