# Generated by Django 4.2 on 2025-04-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0034_alter_cliente_email_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('webpay', 'WebPay'), ('descuento', 'Descuento'), ('giftcard', 'GiftCard'), ('flow', 'FLOW'), ('mercadopago', 'MercadoPago'), ('scotiabank', 'Transferencia ScotiaBank'), ('bancoestado', 'Transferencia BancoEstado'), ('cuentarut', 'Transferencia CuentaRut'), ('machjorge', 'mach jorge'), ('machalda', 'mach alda'), ('bicegoalda', 'bicego alda'), ('bcialda', 'bci alda'), ('andesalda', 'andes alda'), ('mercadopagoaremko', 'mercadopago aremko'), ('scotiabankalda', 'scotiabank alda'), ('copecjorge', 'copec jorge'), ('copecalda', 'copec alda'), ('copecmartin', 'copec martin')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('webpay', 'WebPay'), ('descuento', 'Descuento'), ('giftcard', 'GiftCard'), ('flow', 'FLOW'), ('mercadopago', 'MercadoPago'), ('scotiabank', 'Transferencia ScotiaBank'), ('bancoestado', 'Transferencia BancoEstado'), ('cuentarut', 'Transferencia CuentaRut'), ('machjorge', 'mach jorge'), ('machalda', 'mach alda'), ('bicegoalda', 'bicego alda'), ('bcialda', 'bci alda'), ('andesalda', 'andes alda'), ('mercadopagoaremko', 'mercadopago aremko'), ('scotiabankalda', 'scotiabank alda'), ('copecjorge', 'copec jorge'), ('copecalda', 'copec alda'), ('copecmartin', 'copec martin')], max_length=100),
        ),
    ]
