# Generated by Django 4.2 on 2025-04-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0035_add_transferencia_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='publicado_web',
            field=models.BooleanField(default=True, help_text='Marcar si este servicio debe ser visible y reservable en la página web pública.'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.CharField(choices=[('tina', 'Tina'), ('masaje', 'Masaje'), ('cabana', 'Cabaña'), ('otro', 'Otro')], default='otro', help_text='Tipo de servicio para aplicar lógicas específicas (ej. precios, horarios).', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el servicio está disponible para reservas (uso interno)'),
        ),
    ]
