# Generated by Django 4.2 on 2025-04-07 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0036_add_service_type_visibility_scheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='capacidad_minima',
            field=models.PositiveIntegerField(default=1, help_text='Mínimo de personas para reservar'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='capacidad_maxima',
            field=models.PositiveIntegerField(default=1, help_text='Máximo de personas permitidas'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.proveedor'),
        ),
    ]
