# Generated by Django 4.2 on 2025-04-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0037_servicio_capacidad_minima_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='servicio',
            name='proveedores',
            field=models.ManyToManyField(blank=True, help_text='Selecciona los proveedores (ej. masajistas) que pueden realizar este servicio.', related_name='servicios_ofrecidos', to='ventas.proveedor'),
        ),
    ]
