# Generated by Django 4.2 on 2025-04-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0039_reservaservicio_proveedor_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='descripcion_web',
            field=models.TextField(blank=True, help_text='Descripción detallada para mostrar en la página web pública.', null=True),
        ),
    ]
