# Generated by Django 4.2 on 2025-04-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0040_servicio_descripcion_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaservicio',
            name='imagen',
            field=models.URLField(blank=True, help_text='URL de la imagen externa (ej. Google Cloud Storage)', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.URLField(blank=True, help_text='URL de la imagen externa (ej. Google Cloud Storage)', max_length=1024, null=True),
        ),
    ]
