# Generated by Django 4.2 on 2025-04-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0043_alter_activity_options_alter_campaign_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaservicio',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen representativa de la categoría.', null=True, upload_to='categorias/'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen representativa del servicio.', null=True, upload_to='servicios/'),
        ),
    ]
