# Generated by Django 4.2 on 2025-04-14 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0044_alter_categoriaservicio_imagen_alter_servicio_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_background_image', models.ImageField(blank=True, help_text='Imagen de fondo para la sección principal (hero).', null=True, upload_to='homepage/')),
                ('philosophy_image', models.ImageField(blank=True, help_text="Imagen para la sección 'Vive la Experiencia Aremko'.", null=True, upload_to='homepage/')),
                ('gallery_image_1', models.ImageField(blank=True, help_text="Primera imagen para la galería 'Nuestros Espacios'.", null=True, upload_to='homepage/gallery/')),
                ('gallery_image_2', models.ImageField(blank=True, help_text="Segunda imagen para la galería 'Nuestros Espacios'.", null=True, upload_to='homepage/gallery/')),
                ('gallery_image_3', models.ImageField(blank=True, help_text="Tercera imagen para la galería 'Nuestros Espacios'.", null=True, upload_to='homepage/gallery/')),
            ],
            options={
                'verbose_name': 'Configuración de la Página Principal',
                'verbose_name_plural': 'Configuración de la Página Principal',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='ventas.campaign', verbose_name='Campaña Asociada'),
        ),
    ]
