# Generated by Django 4.2 on 2025-04-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0046_campaign_target_min_spend_campaign_target_min_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='email_body_template',
            field=models.TextField(blank=True, help_text='Usar {nombre_cliente}, {apellido_cliente} como placeholders.', verbose_name='Plantilla Cuerpo Email'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_subject_template',
            field=models.CharField(blank=True, max_length=255, verbose_name='Plantilla Asunto Email'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sms_template',
            field=models.TextField(blank=True, help_text='Usar {nombre_cliente}, {apellido_cliente} como placeholders.', verbose_name='Plantilla SMS'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='whatsapp_template',
            field=models.TextField(blank=True, help_text='Usar {nombre_cliente}, {apellido_cliente} como placeholders.', verbose_name='Plantilla WhatsApp'),
        ),
    ]
