# Generated by Django 4.2 on 2025-04-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0047_campaign_email_body_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='automation_notes',
            field=models.TextField(blank=True, help_text="Describe el flujo de n8n u otra automatización asociada (ej. 'Enviar SMS 3 días después', 'Llamada AI si no abre email').", verbose_name='Notas de Automatización'),
        ),
    ]
