# Generated by Django 4.2 on 2025-04-15 03:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0048_campaign_automation_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('EMAIL_OPEN', 'Email Abierto'), ('EMAIL_CLICK', 'Email Click'), ('SMS_REPLY', 'Respuesta SMS'), ('WHATSAPP_REPLY', 'Respuesta WhatsApp'), ('CALL_ANSWERED', 'Llamada Contestada'), ('CALL_VOICEMAIL', 'Llamada a Buzón de Voz'), ('FORM_SUBMIT', 'Formulario Enviado'), ('OTHER', 'Otro')], max_length=50, verbose_name='Tipo de Interacción')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('details', models.JSONField(blank=True, help_text='Ej: URL clickeada, contenido de respuesta SMS, etc.', null=True, verbose_name='Detalles Adicionales')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='ventas.activity', verbose_name='Actividad Origen')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='ventas.campaign', verbose_name='Campaña')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='ventas.contact', verbose_name='Contacto')),
            ],
            options={
                'verbose_name': 'Interacción de Campaña',
                'verbose_name_plural': 'Interacciones de Campaña',
                'ordering': ['-timestamp'],
            },
        ),
    ]
