# Generated by Django 4.2 on 2025-04-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Dependencia removida - historial de migraciones limpiado
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_background_image', models.ImageField(blank=True, help_text='Imagen de fondo para la sección principal (hero) de la página de inicio.', null=True, upload_to='homepage/')),
            ],
            options={
                'verbose_name': 'Configuración de Inicio',
                'verbose_name_plural': 'Configuraciones de Inicio',
            },
        ),
    ]
