# Generated by Claude Code

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0052_servicehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_template', models.CharField(help_text="Usa {nombre} para insertar el nombre del cliente. Ej: '{nombre}, tenemos algo especial para ti'", max_length=200, verbose_name='Asunto del Email')),
                ('estilo', models.CharField(choices=[('formal', 'Formal/Profesional'), ('calido', 'Cálido/Emocional'), ('ambos', 'Ambos Estilos')], default='calido', max_length=10, verbose_name='Estilo de Email')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para desactivar este asunto temporalmente', verbose_name='Activo')),
                ('veces_usado', models.IntegerField(default=0, help_text='Contador automático de cuántas veces se ha usado', verbose_name='Veces Usado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Asunto de Email',
                'verbose_name_plural': 'Asuntos de Email',
                'ordering': ['estilo', '-activo', 'veces_usado'],
            },
        ),
    ]
