# Generated by Claude Code

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0053_emailsubjecttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'Template Cálido Primavera 2025'", max_length=100, verbose_name='Nombre del Template')),
                ('estilo', models.CharField(choices=[('formal', 'Formal/Profesional'), ('calido', 'Cálido/Emocional')], max_length=10, verbose_name='Estilo de Email')),
                ('activo', models.BooleanField(default=True, help_text='Solo se usa el template activo de cada estilo', verbose_name='Activo')),
                ('saludo', models.TextField(default='Hola {nombre},', help_text="Usa {nombre} para el nombre del cliente. Ej: 'Hola {nombre},'", verbose_name='Saludo')),
                ('introduccion', models.TextField(default='Espero que te encuentres muy bien.', help_text='Texto de apertura. Usa {servicios_narrativa} para la narrativa del historial.', verbose_name='Introducción')),
                ('seccion_ofertas_titulo', models.CharField(default='Oferta Especial', max_length=200, verbose_name='Título de Ofertas')),
                ('seccion_ofertas_intro', models.TextField(default='Este mes tenemos algo especial para ti:', help_text='Texto antes de mostrar las ofertas. Usa {mes_actual} para el mes.', verbose_name='Introducción de Ofertas')),
                ('oferta_texto', models.TextField(default='{oferta_porcentaje} de descuento en {oferta_servicios}', help_text='Usa {oferta_porcentaje} y {oferta_servicios} para ofertas dinámicas.', verbose_name='Texto de Ofertas')),
                ('call_to_action_texto', models.CharField(default='Reservar Ahora', max_length=200, verbose_name='Texto del Botón CTA')),
                ('cierre', models.TextField(default='¡Esperamos verte pronto!', help_text='Texto de cierre del email.', verbose_name='Cierre/Despedida')),
                ('firma', models.TextField(default='Equipo Aremko\nPuerto Varas, Chile', verbose_name='Firma')),
                ('color_principal', models.CharField(default='#2c5530', help_text='Color hexadecimal (ej: #2c5530)', max_length=7, verbose_name='Color Principal')),
                ('color_secundario', models.CharField(default='#8B7355', help_text='Color hexadecimal (ej: #8B7355)', max_length=7, verbose_name='Color Secundario')),
                ('fuente_tipografia', models.CharField(default='Georgia, serif', help_text="Fuente CSS (ej: 'Georgia, serif' o 'Arial, sans-serif')", max_length=100, verbose_name='Tipografía')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Template de Email',
                'verbose_name_plural': 'Templates de Email',
                'ordering': ['estilo', '-activo', '-updated_at'],
            },
        ),
    ]
