# Generated by Claude Code

from django.db import migrations


def create_default_templates(apps, schema_editor):
    """
    Crea templates por defecto para email Cálido y Formal
    """
    EmailContentTemplate = apps.get_model('ventas', 'EmailContentTemplate')

    # Template Cálido
    EmailContentTemplate.objects.create(
        nombre='Template Cálido - Por Defecto',
        estilo='calido',
        activo=True,
        saludo='Hola {nombre},',
        introduccion='Espero que te encuentres muy bien. Nos llena de alegría recordar {servicios_narrativa}. Cada visita tuya nos ha permitido conocerte mejor y saber lo que más te hace feliz.',
        seccion_ofertas_titulo='Un Detalle Especial para Ti',
        seccion_ofertas_intro='Por eso, en agradecimiento a tu lealtad, <strong>este mes de {mes_actual}</strong> queremos tener un detalle especial contigo:',
        oferta_texto='{oferta_texto_completo}',
        call_to_action_texto='Reservar Ahora',
        cierre='''Estos beneficios son válidos durante <strong>todo el mes de {mes_actual}</strong>. Aprovecha esta oportunidad para regalarte el descanso que tanto necesitas antes de que termine el año.

Sabes que para nosotros <strong>no eres un cliente más; eres parte de la familia Aremko</strong>. Nos encantaría volver a verte pronto disfrutando y relajándote como en tus visitas anteriores.

Si te animas a otra escapada, aquí te estaremos esperando con los brazos abiertos, listos para brindarte una vez más una experiencia inolvidable.''',
        firma='''Con cariño,
<strong style="color: #2c5530;">El equipo de Aremko</strong>
<span style="font-size: 14px; color: #999;">Puerto Varas, Chile</span>''',
        color_principal='#2c5530',
        color_secundario='#8B7355',
        fuente_tipografia='Georgia, serif'
    )

    # Template Formal
    EmailContentTemplate.objects.create(
        nombre='Template Formal - Por Defecto',
        estilo='formal',
        activo=True,
        saludo='Estimado/a {nombre},',
        introduccion='En Aremko valoramos tu preferencia y queremos ofrecerte una experiencia única y personalizada basada en {servicios_narrativa}.',
        seccion_ofertas_titulo='Oferta Especial',
        seccion_ofertas_intro='Como parte de nuestro programa de fidelidad, tenemos una oferta exclusiva para ti:',
        oferta_texto='{oferta_texto_completo}',
        call_to_action_texto='Reservar Ahora',
        cierre='¡Esperamos verte pronto en Aremko!',
        firma='''Equipo Aremko
Puerto Varas, Chile''',
        color_principal='#2c5282',
        color_secundario='#4299e1',
        fuente_tipografia='Arial, sans-serif'
    )


def delete_default_templates(apps, schema_editor):
    """
    Elimina los templates por defecto (para revertir la migración)
    """
    EmailContentTemplate = apps.get_model('ventas', 'EmailContentTemplate')
    EmailContentTemplate.objects.filter(
        nombre__in=[
            'Template Cálido - Por Defecto',
            'Template Formal - Por Defecto'
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0054_emailcontenttemplate'),
    ]

    operations = [
        migrations.RunPython(create_default_templates, delete_default_templates),
    ]
