# Generated by manual creation for visual email campaign system
# Date: 2025-12-01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0063_populate_newsletter_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre interno para identificar la campaña', max_length=200, verbose_name='Nombre de la Campaña')),
                ('subject', models.CharField(help_text='Asunto que verán los destinatarios', max_length=500, verbose_name='Asunto del Email')),
                ('html_content', models.TextField(help_text='Contenido del email en formato HTML', verbose_name='Contenido HTML')),
                ('preview_text', models.CharField(blank=True, help_text='Texto que aparece en la vista previa del email', max_length=200, verbose_name='Texto de Preview')),
                ('uses_personalization', models.BooleanField(default=True, help_text='Si usa variables como {{nombre}}, {{email}}, etc.', verbose_name='Usa Personalización')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('ready', 'Lista para Envío'), ('sending', 'Enviando'), ('paused', 'Pausada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Estado')),
                ('audience_type', models.CharField(choices=[('all', 'Todos los suscriptores activos'), ('segment', 'Segmento personalizado'), ('manual', 'Lista manual')], default='all', max_length=20, verbose_name='Tipo de Audiencia')),
                ('segment_filters', models.JSONField(blank=True, default=dict, help_text='Criterios para filtrar destinatarios (JSON)', verbose_name='Filtros de Segmentación')),
                ('batch_size', models.IntegerField(default=25, help_text='Cantidad de emails a enviar por lote', verbose_name='Emails por Lote')),
                ('batch_delay_minutes', models.IntegerField(default=15, help_text='Tiempo de espera entre cada lote de envío', verbose_name='Delay entre Lotes (minutos)')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Fecha y hora para iniciar el envío (null = inmediato)', null=True, verbose_name='Programado para')),
                ('total_recipients', models.IntegerField(default=0, help_text='Número total de destinatarios objetivo', verbose_name='Total de Destinatarios')),
                ('emails_sent', models.IntegerField(default=0, help_text='Cantidad de emails enviados exitosamente', verbose_name='Emails Enviados')),
                ('emails_delivered', models.IntegerField(default=0, help_text='Cantidad de emails que llegaron a destino', verbose_name='Emails Entregados')),
                ('emails_opened', models.IntegerField(default=0, help_text='Cantidad de emails que fueron abiertos', verbose_name='Emails Abiertos')),
                ('emails_clicked', models.IntegerField(default=0, help_text='Cantidad de clicks en links del email', verbose_name='Clicks')),
                ('emails_bounced', models.IntegerField(default=0, help_text='Cantidad de emails que rebotaron', verbose_name='Rebotes')),
                ('spam_complaints', models.IntegerField(default=0, help_text='Cantidad de reportes de spam', verbose_name='Quejas de Spam')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado el')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado el')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Plantilla de Campaña de Email',
                'verbose_name_plural': 'Plantillas de Campañas de Email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email del Destinatario')),
                ('recipient_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Destinatario')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('opened', 'Abierto'), ('clicked', 'Click realizado'), ('bounced', 'Rebotado'), ('failed', 'Fallido'), ('spam', 'Marcado como spam')], default='pending', max_length=20, verbose_name='Estado')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado el')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregado el')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Abierto el')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='Click el')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('bounce_reason', models.CharField(blank=True, max_length=200, verbose_name='Razón del Rebote')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='ventas.emailcampaigntemplate', verbose_name='Campaña')),
            ],
            options={
                'verbose_name': 'Log de Envío de Campaña',
                'verbose_name_plural': 'Logs de Envío de Campañas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaignsendlog',
            index=models.Index(fields=['campaign', 'status'], name='ventas_camp_campaig_0e8e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignsendlog',
            index=models.Index(fields=['recipient_email'], name='ventas_camp_recipie_f3a9c8_idx'),
        ),
    ]
