# Generated by Django 4.2.15 on 2024-12-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0067_update_category_hero_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='visible_en_matriz',
            field=models.BooleanField(
                default=True,
                verbose_name='Visible en Calendario Matriz',
                help_text='Marcar si este servicio debe aparecer en el calendario matriz de disponibilidad.'
            ),
        ),
    ]