apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aremko-booking-system.fullname" . }}
  labels:
    {{- include "aremko-booking-system.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "aremko-booking-system.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aremko-booking-system.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aremko-booking-system.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: google-cloud-key
              mountPath: {{ dir .Values.configMap.data.GOOGLE_APPLICATION_CREDENTIALS }}
              readOnly: true
          envFrom:
            - configMapRef:
                name: {{ include "aremko-booking-system.fullname" . }}-config
            - secretRef:
                name: {{ include "aremko-booking-system.fullname" . }}-secret
      volumes:
        - name: google-cloud-key
          secret:
            secretName: {{ .Values.googleApplicationCredentials.secretName }}
            items:
              - key: {{ .Values.googleApplicationCredentials.secretKey }}
                path: {{ base .Values.configMap.data.GOOGLE_APPLICATION_CREDENTIALS }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 