apiVersion: v2
name: aremko-booking-system
description: A Helm chart for deploying the Aremko Booking System
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: postgresql
  version: "15.5.1"
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.enabled 