# Generated by Django 4.2.30 on 2026-07-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyBriefArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(db_index=True, help_text='Lunes de la semana a la que corresponde el brief.')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('model_analisis', models.CharField(blank=True, default='', help_text='Modelo LLM usado para la pasada de análisis (llamada 1).', max_length=100)),
                ('model_copy', models.CharField(blank=True, default='', help_text='Modelo LLM usado para la pasada de redacción (llamada 2).', max_length=100)),
                ('brief_json', models.JSONField(blank=True, default=dict, help_text='Brief completo (análisis + drafts ya fusionados), tal como se envió.')),
                ('ganchos', models.JSONField(blank=True, default=list, help_text='Frases clave del copy generado esta semana — insumo anti-repetición para la semana siguiente.')),
                ('exito', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Brief semanal archivado',
                'verbose_name_plural': 'Briefs semanales archivados',
                'db_table': 'marketing_briefs_weeklybriefarchive',
                'ordering': ['-generated_at'],
            },
        ),
    ]
