# Generated by Django 4.2.30 on 2026-07-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_briefs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionPlanificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(db_index=True, help_text='Lunes de la semana del brief.')),
                ('dia', models.DateField(db_index=True, help_text='Día planificado de publicación.')),
                ('canal', models.CharField(help_text='Instagram | Instagram Stories | GBP | Email | Facebook', max_length=40)),
                ('tipo', models.CharField(help_text='reel | carrusel | story | post | email', max_length=20)),
                ('pieza_key', models.CharField(help_text='Clave de la pieza en el brief (gbp_post, reel_martes, story_lunes, ...). Única por semana.', max_length=40)),
                ('titulo', models.CharField(blank=True, default='', help_text='Concepto corto de la pieza.', max_length=300)),
                ('copy_json', models.JSONField(blank=True, default=dict, help_text='La pieza completa del brief (guion, caption, hashtags, etc.) lista para usar.')),
                ('responsable', models.CharField(blank=True, default='', max_length=60)),
                ('tiempo_estimado', models.CharField(blank=True, default='', max_length=60)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_produccion', 'En producción'), ('lista', 'Lista para publicar'), ('publicada', 'Publicada'), ('no_aplica', 'No aplica esta semana')], db_index=True, default='pendiente', max_length=20)),
                ('material_urls', models.JSONField(blank=True, default=list, help_text='URLs del material subido por Angélica (fotos/videos en Cloudinary). Fase 2.')),
                ('notas_revision', models.TextField(blank=True, default='', help_text='Feedback del revisor IA sobre el material subido. Fase 2.')),
                ('published_url', models.CharField(blank=True, default='', help_text='Link del post ya publicado (para colgarle métricas). Fase 3.', max_length=500)),
                ('metricas', models.JSONField(blank=True, default=dict, help_text='Métricas de la publicación, actualizadas semanalmente. Fase 3.')),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publicación planificada',
                'verbose_name_plural': 'Publicaciones planificadas',
                'db_table': 'marketing_briefs_publicacionplanificada',
                'ordering': ['dia', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='publicacionplanificada',
            constraint=models.UniqueConstraint(fields=('semana_inicio', 'pieza_key'), name='uniq_publicacion_semana_pieza'),
        ),
    ]
