# Generated by Django 4.2.30 on 2026-07-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_briefs', '0002_publicacionplanificada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacionplanificada',
            name='revision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacionplanificada',
            name='revision_json',
            field=models.JSONField(blank=True, default=list, help_text='Correcciones estructuradas de la última revisión IA (lista de {aspecto, severidad, encontrado, correccion}).'),
        ),
        migrations.AddField(
            model_name='publicacionplanificada',
            name='revision_resumen',
            field=models.TextField(blank=True, default='', help_text='Veredicto en 1-2 frases del revisor IA.'),
        ),
        migrations.AddField(
            model_name='publicacionplanificada',
            name='revision_veredicto',
            field=models.CharField(choices=[('sin_revisar', 'Sin revisar'), ('revisando', 'Revisando…'), ('con_observaciones', 'Con observaciones'), ('aprobado', 'Aprobado')], db_index=True, default='sin_revisar', help_text='Resultado de la última revisión IA del material subido.', max_length=20),
        ),
        migrations.AlterField(
            model_name='publicacionplanificada',
            name='material_urls',
            field=models.JSONField(blank=True, default=list, help_text='URLs del material subido por Angélica (fotos/carruseles en Cloudinary).'),
        ),
        migrations.AlterField(
            model_name='publicacionplanificada',
            name='notas_revision',
            field=models.TextField(blank=True, default='', help_text='(Legado / notas libres de revisión.)'),
        ),
    ]
