# Generated by Django 4.2.30 on 2026-04-23 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AremkoRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('context_key', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('message_text', models.TextField()),
                ('recommended_service_type', models.CharField(blank=True, max_length=50)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Recomendación Aremko',
                'verbose_name_plural': 'Recomendaciones Aremko',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.TextField(blank=True)),
                ('primary_interest', models.CharField(choices=[('NATURE', 'Naturaleza'), ('GASTRONOMY', 'Gastronomía'), ('ADVENTURE', 'Aventura'), ('RELAX_ROMANTIC', 'Relax / Romántico'), ('MIXED', 'Mixto')], db_index=True, max_length=30)),
                ('recommended_profile', models.CharField(blank=True, choices=[('COUPLE', 'Pareja'), ('FAMILY', 'Familia'), ('FRIENDS', 'Amigos'), ('SOLO', 'Solo/a')], max_length=20)),
                ('is_romantic', models.BooleanField(default=False)),
                ('is_family_friendly', models.BooleanField(default=False)),
                ('is_adventure', models.BooleanField(default=False)),
                ('is_rain_friendly', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('published', models.BooleanField(db_index=True, default=False)),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Circuito',
                'verbose_name_plural': 'Circuitos',
                'ordering': ['sort_order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='CircuitDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('block_type', models.CharField(choices=[('ARRIVAL', 'Llegada'), ('HALF_DAY', 'Medio día'), ('FULL_DAY', 'Día completo'), ('DEPARTURE', 'Salida'), ('AREMKO_MOMENT', 'Momento Aremko')], max_length=30)),
                ('summary', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='destino_puerto_varas.circuit')),
            ],
            options={
                'verbose_name': 'Día de circuito',
                'verbose_name_plural': 'Días de circuito',
                'ordering': ['circuit', 'day_number', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='DurationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('duration_type', models.CharField(choices=[('HALF_DAY', 'Medio día'), ('FULL_DAY', 'Día completo'), ('TWO_DAYS_ONE_NIGHT', '2 días / 1 noche'), ('THREE_DAYS_TWO_NIGHTS', '3 días / 2 noches'), ('FOUR_DAYS_THREE_NIGHTS', '4 días / 3 noches'), ('FIVE_DAYS_FOUR_NIGHTS', '5 días / 4 noches'), ('SIX_DAYS_FIVE_NIGHTS', '6 días / 5 noches'), ('SEVEN_DAYS_SIX_NIGHTS', '7 días / 6 noches')], max_length=30)),
                ('days', models.PositiveSmallIntegerField()),
                ('nights', models.PositiveSmallIntegerField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Caso de duración',
                'verbose_name_plural': 'Casos de duración',
                'ordering': ['sort_order', 'days'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('place_type', models.CharField(choices=[('ATTRACTION', 'Atracción'), ('RESTAURANT', 'Restaurante'), ('ACTIVITY', 'Actividad'), ('VIEWPOINT', 'Mirador'), ('CAFE', 'Café'), ('SHOP', 'Tienda'), ('PARK', 'Parque'), ('MUSEUM', 'Museo'), ('OTHER', 'Otro')], db_index=True, max_length=30)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.TextField(blank=True)),
                ('location_label', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_rain_friendly', models.BooleanField(default=False)),
                ('is_romantic', models.BooleanField(default=False)),
                ('is_family_friendly', models.BooleanField(default=False)),
                ('is_adventure_related', models.BooleanField(default=False)),
                ('practical_tips', models.TextField(blank=True)),
                ('safety_notes', models.TextField(blank=True)),
                ('did_you_know', models.TextField(blank=True)),
                ('nobody_tells_you', models.TextField(blank=True)),
                ('published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TravelTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tip_text', models.TextField()),
                ('interest', models.CharField(blank=True, choices=[('NATURE', 'Naturaleza'), ('GASTRONOMY', 'Gastronomía'), ('ADVENTURE', 'Aventura'), ('RELAX_ROMANTIC', 'Relax / Romántico'), ('MIXED', 'Mixto')], max_length=30)),
                ('profile', models.CharField(blank=True, choices=[('COUPLE', 'Pareja'), ('FAMILY', 'Familia'), ('FRIENDS', 'Amigos'), ('SOLO', 'Solo/a')], max_length=20)),
                ('applies_when_raining', models.BooleanField(default=False)),
                ('applies_when_sunny', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('duration_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_tips', to='destino_puerto_varas.durationcase')),
            ],
            options={
                'verbose_name': 'Tip de viaje',
                'verbose_name_plural': 'Tips de viaje',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('interest', models.CharField(blank=True, choices=[('NATURE', 'Naturaleza'), ('GASTRONOMY', 'Gastronomía'), ('ADVENTURE', 'Aventura'), ('RELAX_ROMANTIC', 'Relax / Romántico'), ('MIXED', 'Mixto')], max_length=30)),
                ('profile', models.CharField(blank=True, choices=[('COUPLE', 'Pareja'), ('FAMILY', 'Familia'), ('FRIENDS', 'Amigos'), ('SOLO', 'Solo/a')], max_length=20)),
                ('is_rainy', models.BooleanField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('duration_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_rules', to='destino_puerto_varas.durationcase')),
                ('recommended_circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_rules', to='destino_puerto_varas.circuit')),
            ],
            options={
                'verbose_name': 'Regla de recomendación',
                'verbose_name_plural': 'Reglas de recomendación',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeadConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('INSTAGRAM', 'Instagram'), ('WEB', 'Web')], db_index=True, max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada'), ('WAITING_USER', 'Esperando usuario'), ('QUALIFIED', 'Calificada'), ('REFERRED_TO_AREMKO', 'Derivada a Aremko')], db_index=True, default='OPEN', max_length=30)),
                ('detected_interest', models.CharField(blank=True, choices=[('NATURE', 'Naturaleza'), ('GASTRONOMY', 'Gastronomía'), ('ADVENTURE', 'Aventura'), ('RELAX_ROMANTIC', 'Relax / Romántico'), ('MIXED', 'Mixto')], max_length=30)),
                ('detected_profile', models.CharField(blank=True, choices=[('COUPLE', 'Pareja'), ('FAMILY', 'Familia'), ('FRIENDS', 'Amigos'), ('SOLO', 'Solo/a')], max_length=20)),
                ('referred_to_aremko', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detected_duration_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='destino_puerto_varas.durationcase')),
                ('recommended_circuit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='destino_puerto_varas.circuit')),
            ],
            options={
                'verbose_name': 'Conversación de lead',
                'verbose_name_plural': 'Conversaciones de leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('USER', 'Usuario'), ('ASSISTANT', 'Asistente'), ('AGENT', 'Agente humano'), ('SYSTEM', 'Sistema')], max_length=20)),
                ('text', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='destino_puerto_varas.leadconversation')),
            ],
            options={
                'verbose_name': 'Mensaje de conversación',
                'verbose_name_plural': 'Mensajes de conversación',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CircuitPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_order', models.PositiveSmallIntegerField(default=0)),
                ('is_main_stop', models.BooleanField(default=False)),
                ('circuit_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_stops', to='destino_puerto_varas.circuitday')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circuit_stops', to='destino_puerto_varas.place')),
            ],
            options={
                'verbose_name': 'Parada de circuito',
                'verbose_name_plural': 'Paradas de circuito',
                'ordering': ['circuit_day', 'visit_order'],
            },
        ),
        migrations.AddField(
            model_name='circuit',
            name='duration_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circuits', to='destino_puerto_varas.durationcase'),
        ),
        migrations.AddConstraint(
            model_name='circuitday',
            constraint=models.UniqueConstraint(fields=('circuit', 'day_number'), name='uq_circuitday_circuit_day'),
        ),
    ]
