# Generated by Django 4.2.30 on 2026-04-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destino_puerto_varas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadconversation',
            name='last_assistant_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadconversation',
            name='last_user_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadconversation',
            name='showed_interest_in_aremko',
            field=models.BooleanField(default=False, help_text='True si el usuario mencionó spa/masaje/tina/alojamiento durante la conversación.'),
        ),
    ]
