# Generated by Django 4.2.30 on 2026-04-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destino_puerto_varas', '0005_add_external_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadconversation',
            name='channel',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('INSTAGRAM', 'Instagram'), ('WEB', 'Web'), ('TELEGRAM', 'Telegram')], db_index=True, max_length=20),
        ),
    ]
